global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'zedelivery'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:9090' ]